;;Tile Object
(define-object (tile-obj symbol x y z passable visible blocks-vision living item)
    ((get-symbol    (lambda () symbol))
     (set-symbol    (lambda (new-symbol) (set! symbol new-symbol)))
     (get-x         (lambda () x))
     (set-x         (lambda (new-x) (set! x new-x)))
     (get-y         (lambda () y))
     (set-y         (lambda (new-y) (set! y new-y)))
     (get-z         (lambda () z))
     (set-z         (lambda (new-z) (set! z new-z)))
     (get-passable  (lambda () passable))
     (set-passable  (lambda (new-passable) (set! passable new-passable)))
     (get-visible   (lambda () visible))
     (set-visible   (lambda (new-visible) (set! visible new-visible)))
     (get-blocks-vision  (lambda () blocks-vision))
     (set-blocks-vision  (lambda (new-blocks-vision) (set! blocks-vision new-blocks-vision)))
     (get-living    (lambda () living))
     (set-living    (lambda (new-living) (set! living new-living)))
     (get-item      (lambda () item))
     (set-item      (lambda (new-item) (set! item new-item)))
     ))
